site_name: Datetime-Selenium
docs_dir: docs_md
site_dir: docs
repo_url: https://github.com/dsbowen/datetime-selenium
edit_uri: edit/master/docs_md
nav:
  - Home: index.md
  - Get datetime objects: requests.md
  - API : api.md
theme: readthedocs
extra_css:
  - css/extra.css